# Generated by Django 6.0 on 2025-12-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='branch',
            field=models.CharField(max_length=100),
        ),
    ]
