# Generated by Django 6.0 on 2025-12-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_moviebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=200)),
                ('bookprice', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
                ('booktype', models.CharField(max_length=50)),
            ],
        ),
    ]
